version: "3.9"

services:
  # 1. Servicio 'builder' → genera la imagen sólo una vez
  maquina-base:
    build:
      context: ./maquinas
      dockerfile: maquina-base.Dockerfile
    image: maquina-base:latest        # <- etiqueta resultante
    # Este contenedor no necesita arrancar; basta con que exista la imagen
    entrypoint: ["true"]

  # 2. Cada máquina usa esa imagen
  maquina1:
    image: maquina-base:latest
    container_name: maquina1
    volumes:
      - ./data/maquina1:/home/users/documentos

  maquina2:
    image: maquina-base:latest
    container_name: maquina2
    volumes:
      - ./data/maquina2:/home/users/documentos

  maquina3:
    image: maquina-base:latest
    container_name: maquina3
    volumes:
      - ./data/maquina3:/home/users/documentos