version: "3.9"

services:
  maquina-base:
    build:
      context: ./maquinas
      dockerfile: maquina-base.Dockerfile
    image: maquina-base:latest
    entrypoint: ["true"]

  maquina1:
    image: maquina-base:latest
    container_name: maquina1
    volumes:
      - ./data/maquina1:/home/users/documentos

  maquina2:
    image: maquina-base:latest
    container_name: maquina2
    volumes:
      - ./data/maquina2:/home/users/documentos

  maquina3:
    image: maquina-base:latest
    container_name: maquina3
    volumes:
      - ./data/maquina3:/home/users/documentos

  backup:
    build: ./backup
    container_name: backup
    volumes:
      - ./backups:/home
    depends_on:
      - maquina1
      - maquina2
      - maquina3

  explorador:
    build: ./explorador
    container_name: explorador
    ports:
      - "8080:8080"
    volumes:
      - ./alertas:/home/alertas_detectadas
    depends_on:
      - backup